import type { Metadata } from "next";

import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import Navbar from "@/components/Navbar";








export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
     
 
      <body
      className="bg-[#0C0C0C]" 
      >
         <ThemeProvider
         attribute="class"
         defaultTheme="system"
         enableSystem
         disableTransitionOnChange>
          <Navbar/>
       
          <main className="lg:mx-[140px] bg-[#0C0C0C]">

          {/* container to center the content */}
         
            {children}
           
          </main>
        
        
        </ThemeProvider>
      
      </body>

      

    </html>
  );
}
